### ISSUE TITLE
NanoVNA-App.exe not working on Windows 7

### ISSUE THREAD

**Issue by EA4BFK** [OneOfEleven/NanoVNA-H#1]
Hi, several days ago I donwloaded the release 1.1.135 and it was working perfectly on my Windows 7 PC, latest releases doesn't start at all.
IN fact the size of the file is much smaller than the 1.1.35 wersion.

Thanks

Alex
EA4BFK

**Comment by OneOfEleven** [comment]
> Hi, several days ago I donwloaded the release 1.1.135 and it was working perfectly on my Windows 7 PC, latest releases doesn't start at all.
> IN fact the size of the file is much smaller than the 1.1.35 wersion.

Pardon ?

Sounds like you're doing something wrong somewhere, it's been some weeks since I did that version!

**Comment by EA4BFK** [comment]
HI,

Yes I was downloading in long way. Sorry for bother you, and thanks for your development

AleX
EA4BFK
