### ISSUE TITLE
Bandwidth Command Format Not Accepted by my device

### ISSUE THREAD

**Issue by saharbin** [OneOfEleven/NanoVNA-H#2]
Beginning in version 54: According to the comms terminal, the device is sent: "bandwidth 2000 Hz".  This gets interpreted as 9 Hz by the device.  Prior versions send: "bandwidth 0".  This gets interpreted as 2000 Hz by the device.

Seep does not work properly.  Unsure if this is because the bandwidth is not set properly.

Attaching a copy of the comms session.

[nanovna_commands_2020_Sep_04_07_59_41.txt](https://github.com/OneOfEleven/NanoVNA-H/files/5175015/nanovna_commands_2020_Sep_04_07_59_41.txt)

**Comment by OneOfEleven** [comment]
Yes I need to update the firmware to now work with the current PC software properly.

Bare with me if you can, I'll see to it today and update my firmware to match all the PC software changes.

**Comment by OneOfEleven** [comment]
It should be OK now.

**Comment by saharbin** [comment]
Works great as of v59. Requires reflashing firmware.  Thanks OneOfEleven!
